### ISSUE TITLE
Problems with Node v10.3.0

### ISSUE THREAD

**Issue by mb8z** [tom-james-watson/wallpaper-macos#2]
I'm trying to install your package with node v10.3.0 installed and all I get is:
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:360:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value str(in);
                      ^
/Users/nyc/.node-gyp/10.3.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/nyc/.node-gyp/10.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/binding.cc:435:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value str(in);
                      ^
/Users/nyc/.node-gyp/10.3.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/nyc/.node-gyp/10.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/binding.cc:619:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<v8::String>("endianness").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
  ~~~~~~  ^
../src/binding.cc:620:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
  ~~~~~~  ^
2 warnings and 2 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/10.3.0/bin/node" "/usr/local/Cellar/node/10.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

```

Any idea why this might be happening? Not a real expert in node here :(

**Comment by tom-james-watson** [comment]
What version of macOS are you using?

I believe you will need the latest xcode command line tools installed. Have you done that?

**Comment by mb8z** [comment]
Thanks for the quick response :tada:
I'm on Mojave Public Beta 5 and Xcode 10 is downloading in this moment. Do you think installing it along with `xcode-select --install` will do the trick?

**Comment by tom-james-watson** [comment]
Definitely a good step to try!

**Comment by mb8z** [comment]
Same findings as previously. Node updated to 10.8.0 and Xcode to its latest Beta release. I've searched the net and it seems to be a problem with node version and a package that still uses old code or something. Not really sure 😞

**Comment by tom-james-watson** [comment]
I managed to recreate the bug. Looks like nodobjc has some incompatibility with the latest node version. I think until they release a fix you should stick with the LTS version of node (which is always going to be more stable anyway).

In case you don't know about it, the easiest way is to use [n](https://github.com/tj/n). You can simply do:

```
sudo n 8.11.3
```

**Comment by mb8z** [comment]
Thanks a lot! :)
