### ISSUE TITLE
Failure on npm install for node-gyp rebuild

### ISSUE THREAD

**Issue by hisnameisjimmy** [tom-james-watson/wallpaper-macos#3]
Deets:
- MacOS Catalina 10.15.5
- NodeJS v12.18.3 LTS

I'm guessing it's the same problem found by the other surfer a few years ago: https://github.com/tom-james-watson/wallpaper-macos/issues/2

It does look like [nodobjc](https://github.com/TooTallNate/NodObjC/) was abandoned, although there are people trying to fix it: https://github.com/TooTallNate/NodObjC/pull/119

Logs:
```
> ref@1.1.3 install node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:222:30: error: no matching member function for call to 'BooleanValue'
  bool persistent = info[3]->BooleanValue();
                    ~~~~~~~~~^~~~~~~~~~~~
/Users/hookermbp/Library/Caches/node-gyp/12.18.3/include/node/v8.h:2699:8: note: candidate function not viable: requires single
      argument 'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/hookermbp/Library/Caches/node-gyp/12.18.3/include/node/v8.h:2702:51: note: candidate function not viable: requires single
      argument 'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../src/binding.cc:253:38: error: too few arguments to function call, single argument 'context' was not specified
  size_t size = info[2]->Uint32Value();

.....

51 warnings and 8 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd node_modules/ref
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN art-diario@1.0.0 No repository field.
npm WARN art-diario@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by tom-james-watson** [comment]
Yup looks like this needs fixing upstream, so blocked by https://github.com/TooTallNate/NodObjC/pull/119
